export const ADD_ENTRY = 'ADD_ENTRY';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const TOGGLE_STATUS = 'TOGGLE_STATUS';

export const UPDATE_MEAL_SUGGESTIONS = 'UPDATE_MEAL_SUGGESTIONS';
export const REMOVE_DUPLICATES = 'REMOVE_DUPLICATES';
